### ISSUE TITLE
Sharing information incomplete after user joins organization.

### ISSUE THREAD

**Issue by lgutro** [lgutro/hello-world#118] opened 2019-03-27 17:50 UTC
After an organization is created by an admin, a new user is invited, and the new user accepts, I expect that when the  admin goes to the 'Sharing' page, that it will show GroupName/User on both sections ('Shared With Me' and 'Sharing With').  However, I only see GroupName/User on the section 'Shared With Me'.  It should report that that their own data can be viewed.

![Capture](https://user-images.githubusercontent.com/38503093/55100586-95ccf880-5098-11e9-904d-e333125c54ae.JPG)

Likewise the user doesn't see that his own data is being shared:
![Capture](https://user-images.githubusercontent.com/38503093/55100415-3ec72380-5098-11e9-8053-bf56d80ab05d.JPG)

**Comment by sharifyounes** [comment] 2019-03-28 19:18
Yeah -- that's bad UX, but unfortunately I logically intended it to be that way. Not a bug for now... but should be fixed eventually.

**Closed as completed** 2019-04-01 13:41 UTC
